### ISSUE TITLE
Errore in avvio di HA

### ISSUE THREAD

**Issue by alessandrobenevelli** [Home-Assistant-Pro-Team/Power-Control#1]
Ciao, ho installato e configurato come indicato il package ma al riavvio di HA nel log appaiono questi errori:

`home-assistant    | 2023-06-30 19:39:58.917 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'split' when rendering '{% set a = states('sensor.check_ultimo_acceso').split() %} {% set b = state_attr('sensor.check_ultimo_acceso', 'old_state').split() %} {% set result = (a|list|reject('in', b)|list)[0] %}
home-assistant    |   {{ result if result is defined else 'Nessuno' }}'
home-assistant    | 2023-06-30 19:39:58.954 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set a = states('sensor.check_ultimo_acceso').split() %} {% set b = state_attr('sensor.check_ultimo_acceso', 'old_state').split() %} {% set result = (a|list|reject('in', b)|list)[0] %}
home-assistant    |   {{ result if result is defined else 'Nessuno' }}) renders=2>
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 563, in async_render
home-assistant    |     render_result = _render_with_context(self.template, compiled, **kwargs)
home-assistant    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2179, in _render_with_context
home-assistant    |     return template.render(**kwargs)
home-assistant    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
home-assistant    |     self.environment.handle_exception()
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
home-assistant    |     raise rewrite_traceback_stack(source=source)
home-assistant    |   File "<template>", line 1, in top-level template code
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
home-assistant    |     if not __self.is_safe_callable(__obj):
home-assistant    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2511, in is_safe_callable
home-assistant    |     return isinstance(obj, AllStates) or super().is_safe_callable(obj)
home-assistant    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
home-assistant    |     getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
home-assistant    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2205, in _fail_with_undefined_error
home-assistant    |     raise ex
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2196, in _fail_with_undefined_error
home-assistant    |     return super()._fail_with_undefined_error(*args, **kwargs)
home-assistant    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    | jinja2.exceptions.UndefinedError: 'None' has no attribute 'split'
home-assistant    | 
home-assistant    | The above exception was the direct cause of the following exception:
home-assistant    | 
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 684, in async_render_to_info
home-assistant    |     render_info._result = self.async_render(variables, strict=strict, **kwargs)
home-assistant    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 565, in async_render
home-assistant    |     raise TemplateError(err) from err
home-assistant    | homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'split'
home-assistant    | 2023-06-30 19:39:58.973 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'split' when rendering '{% set a = states('sensor.check_ultimo_acceso').split() %} {% set b = state_attr('sensor.check_ultimo_acceso', 'old_state').split() %} {% set result = (a|list|reject('in', b)|list)[0] %}
home-assistant    |   {{ result if result is defined else 'Nessuno' }}'
home-assistant    | 2023-06-30 19:39:58.979 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'split'') while processing template 'Template<template=({% set a = states('sensor.check_ultimo_acceso').split() %} {% set b = state_attr('sensor.check_ultimo_acceso', 'old_state').split() %} {% set result = (a|list|reject('in', b)|list)[0] %}
home-assistant    |   {{ result if result is defined else 'Nessuno' }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.ultimo_dispositivo_acceso'
home-assistant    | 2023-06-30 19:39:59.113 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 380, in _async_template_startup
home-assistant    |     result_info.async_refresh()
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 974, in async_refresh
home-assistant    |     self._refresh(None)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1154, in _refresh
home-assistant    |     self.hass.async_run_hass_job(self._job, event, updates)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/core.py", line 618, in async_run_hass_job
home-assistant    |     hassjob.target(*args)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 349, in _handle_results
home-assistant    |     self.async_write_ha_state()
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
home-assistant    |     self._async_write_ha_state()
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in _async_write_ha_state
home-assistant    |     hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/core.py", line 1637, in async_set
home-assistant    |     state = State(
home-assistant    |             ^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in __init__
home-assistant    |     raise InvalidStateError(
home-assistant    | homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.lista_carichi. State max length is 255 characters.
home-assistant    | 2023-06-30 19:39:59.317 WARNING (MainThread) [homeassistant.components.template.trigger] Error initializing 'template' trigger for 'Power control': TypeError: float() argument must be a string or a real number, not 'NoneType'
home-assistant    | 2023-06-30 19:39:59.344 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ now() > as_datetime(state_attr('timer.distacco_carico', 'finishes_at')) - timedelta(minutes=2) }}) renders=3>
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 563, in async_render
home-assistant    |     render_result = _render_with_context(self.template, compiled, **kwargs)
home-assistant    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2179, in _render_with_context
home-assistant    |     return template.render(**kwargs)
home-assistant    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
home-assistant    |     self.environment.handle_exception()
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
home-assistant    |     raise rewrite_traceback_stack(source=source)
home-assistant    |   File "<template>", line 1, in top-level template code
home-assistant    |   File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
home-assistant    |     return __context.call(__obj, *args, **kwargs)
home-assistant    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1815, in as_datetime
home-assistant    |     timestamp = float(value)
home-assistant    |                 ^^^^^^^^^^^^
home-assistant    | TypeError: float() argument must be a string or a real number, not 'NoneType'
home-assistant    | 
home-assistant    | The above exception was the direct cause of the following exception:
home-assistant    | 
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 684, in async_render_to_info
home-assistant    |     render_info._result = self.async_render(variables, strict=strict, **kwargs)
home-assistant    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 565, in async_render
home-assistant    |     raise TemplateError(err) from err
home-assistant    | homeassistant.exceptions.TemplateError: TypeError: float() argument must be a string or a real number, not 'NoneType'
`

Che cosa ho sbagliato?

Grazie per il supporto.
Alessandro

**Comment by marco-hacs** [comment]
Non è un errore tuo... ma semplicemente è un errore che da in fase di avvio di ha (ma non compromette il funzionamento) perché il sensore è vuoto e non può applicare la funzione split. Non chiudere issue che lo sistemo come ho 2 minuti.

**Comment by alessandrobenevelli** [comment]
Ok grazie mille. Ti segnalo anche se quando provo a cliccare sui due primi pulsanti della card (dispositivi da escludere e gestione dei carichi) non si apre il pop-up... non fanno nulla. Invece le altre due (notifiche e speaker) cambiano stato correttamente.

**Comment by marco-hacs** [comment]
Questo dipende da browsermod. Se lo hai appena installato svuota la cache del browser.

**Comment by marco-hacs** [comment]
Aggiornato nella - Version: 1.3 -

**Comment by marco-hacs** [comment]
Aggiornato nella - Version: 1.3 -
