### ISSUE TITLE
Soglia brekkata ma annuncio nessun carico da staccare.

### ISSUE THREAD

**Issue by fiorentino77** [Home-Assistant-Pro-Team/Power-Control#3]
Come da titolo, gli speaker annunciano il break della soglia impostata ed in quel momento ci sono carichi inseriti in lista che assorbono.
Nonostante questo nessun carico viene staccato.
Probabilmente, dico io, non ha il tempo necessario per procedere con lo spegnimento dei carichi perche' la soglia, da sola, torna sotto il livello di attenzione.

Tempo di distacco impostato: 90min.
Settaggi:

```
{% macro entities_control() %}
    {% set list_entities =
         [
			'switch.shelly1pm_98cdac2fae5e',
      'switch.shelly1pm_485519023baf',
			'switch.shelly1pm_76df3c',
			'climate.condizionatore_aria_matrimoniale',
      'climate.condizionatore_aria_niccolo',
      'climate.condizionatore_aria_emma',
			'switch.shelly1pm_76b488',
			'switch.shelly1pm_76606b',
      'switch.shelly1pm_765fc7',
      'switch.shelly1pm_76e76d',
      'switch.shelly1pm_765dbf',
      'switch.shelly1pm_766078'
         ]
    %}
    {% for d in list_entities %}
        {{ d }}
    {% endfor %}
{% endmacro %}

{% macro power_control() %}
	{
		"Sensore W": "sensor.consumo_istantaneo"
	}
{% endmacro %}
```

Grazie.

**Comment by marco-hacs** [comment]
2 minuti prima dei distacchi si riceve una notifica di avviso soglia elevata... quindi nel tuo caso dopo 88minuti... mentre 90 dovrebbe staccare.

Sei sicuro che ha 90 i carichi sono ancora accesi?

**Comment by fiorentino77** [comment]
No assolutamente, io ho impostato 90minuti ma lo speaker annuncia il break della soglia all'istante, non dopo 88 minuti.

**Comment by marco-hacs** [comment]
![image](https://github.com/Home-Assistant-Pro-Team/Power-Control/assets/62516592/8fa37e07-cd66-4518-bccb-460f20689813)

**Comment by marco-hacs** [comment]
riesci a mandare la traccia dell'automazione?

**Comment by fiorentino77** [comment]
> riesci a mandare la traccia dell'automazione?

Screeshot: https://i.imgur.com/JIsENBH.png

Screenshot 2: https://i.imgur.com/ouJjMHm.png

**Comment by marco-hacs** [comment]
```
{% from 'power_control.jinja' import list_device %}
{% set power = list_device().split() %}
  {{ power }}
```

Questo dovrebbe restituire la lista dei dispositivi presenti nella lista accesi. Provalo in strumento per sviluppatori

**Comment by fiorentino77** [comment]
> ```
> {% from 'power_control.jinja' import list_device %}
> {% set power = list_device().split() %}
>   {{ power }}
> ```
> 
> Questo dovrebbe restituire la lista dei dispositivi presenti nella lista accesi. Provalo in strumento per sviluppatori

Ecco:  https://i.imgur.com/VA5eLx1.png

**Comment by marco-hacs** [comment]
Ma sono accesi?

**Comment by fiorentino77** [comment]
> Ma sono accesi?

Ahaa, si certo :)
Avevo fatto la prova accendendo il Termoventilatore, ovvero il primo nella lista dei carichi da staccare.
Ecco gli screenshots:

https://i.imgur.com/ydlLG1L.png
https://i.imgur.com/IPnh7Ye.png
Risultato sempre il medesimo: https://i.imgur.com/K04w3qP.png

**Comment by marco-hacs** [comment]
Molto strano non vorrei che hai cambiato qualcosa... se ho ben capito stai usando shelly 1pm... ma io con li stessi rele non riscontro questi problemi. Come sono integrati? integrazione ufficiale? mqtt? 

Come prima cosa accertati di vedere la lista
``` {{states('sensor.lista_carichi').split() }} ```

Questo è il template della macro che deve vedere i dispositivi accesi... se qui non appaiono non scegnerà mai niente.
```
    {% set output = namespace(sensor_power_off=[],result=[]) %}
    {%- set list = states('sensor.lista_carichi').split() -%}
    {%- set filter = states| selectattr('entity_id', 'in', list) |rejectattr('state', 'in',['off', 'unavailable', 'unknown'])|map(attribute='entity_id')|list-%}
    {%-  for on_power_off in list if on_power_off in filter  -%}
        {% set id = device_id(on_power_off)%}
        {%- set sensor_power =expand(device_entities(id))|selectattr('entity_id', 'match', 'sensor.')|selectattr('attributes.device_class', 'defined')| selectattr('attributes.device_class', 'eq', 'power') | map(attribute='entity_id')|list %}
        {%- for power in sensor_power if states(power)|int(0) < 15-%}
            {%- set output.sensor_power_off = output.sensor_power_off + [on_power_off] -%}
        {% endfor %}
    {% endfor %}
    {% for t in list if t in filter and not t in output.sensor_power_off %}
        {{t}}
    {% endfor %}
```

Se non va mandami uno screen (migliore) con questo template.

```
    {% set output = namespace(sensor_power_off=[],result=[]) %}
    {%- set list =          [
			'switch.shelly1pm_98cdac2fae5e',
      'switch.shelly1pm_485519023baf',
			'switch.shelly1pm_76df3c',
			'climate.condizionatore_aria_matrimoniale',
      'climate.condizionatore_aria_niccolo',
      'climate.condizionatore_aria_emma',
			'switch.shelly1pm_76b488',
			'switch.shelly1pm_76606b',
      'switch.shelly1pm_765fc7',
      'switch.shelly1pm_76e76d',
      'switch.shelly1pm_765dbf',
      'switch.shelly1pm_766078'
         ] -%}
    {%- set filter = states| selectattr('entity_id', 'in', list) |rejectattr('state', 'in',['off', 'unavailable', 'unknown'])|map(attribute='entity_id')|list-%}
    {%-  for on_power_off in list if on_power_off in filter  -%}
        {% set id = device_id(on_power_off)%}
        ID DISCPOSITIVO {{ id }}
        {%- set sensor_power =expand(device_entities(id))|selectattr('entity_id', 'match', 'sensor.')|selectattr('attributes.device_class', 'defined')| selectattr('attributes.device_class', 'eq', 'power') | map(attribute='entity_id')|list %}
        SENSORE POWER {{ sensor_power }}
        {%- for power in sensor_power if states(power)|int(0) < 15-%}
        ASSORBIMENTO INFERIORE AI 15w:  {{ states(power) }} w
            {%- set output.sensor_power_off = output.sensor_power_off + [on_power_off] -%}
        {% endfor %}
    {% endfor %}
    {% for t in list if t in filter and not t in output.sensor_power_off %}
        RISULTATO CORRETTO:{{t}}
    {% endfor %}
```

**Comment by fiorentino77** [comment]
> Molto strano non vorrei che hai cambiato qualcosa... se ho ben capito stai usando shelly 1pm... ma io con li stessi rele non riscontro questi problemi. Come sono integrati? integrazione ufficiale? mqtt?
> 
> Come prima cosa accertati di vedere la lista `{{states('sensor.lista_carichi').split() }}`
> 
> Questo è il template della macro che deve vedere i dispositivi accesi... se qui non appaiono non scegnerà mai niente.
> 
> ```
>     {% set output = namespace(sensor_power_off=[],result=[]) %}
>     {%- set list = states('sensor.lista_carichi').split() -%}
>     {%- set filter = states| selectattr('entity_id', 'in', list) |rejectattr('state', 'in',['off', 'unavailable', 'unknown'])|map(attribute='entity_id')|list-%}
>     {%-  for on_power_off in list if on_power_off in filter  -%}
>         {% set id = device_id(on_power_off)%}
>         {%- set sensor_power =expand(device_entities(id))|selectattr('entity_id', 'match', 'sensor.')|selectattr('attributes.device_class', 'defined')| selectattr('attributes.device_class', 'eq', 'power') | map(attribute='entity_id')|list %}
>         {%- for power in sensor_power if states(power)|int(0) < 15-%}
>             {%- set output.sensor_power_off = output.sensor_power_off + [on_power_off] -%}
>         {% endfor %}
>     {% endfor %}
>     {% for t in list if t in filter and not t in output.sensor_power_off %}
>         {{t}}
>     {% endfor %}
> ```
> 
> Se non va mandami uno screen (migliore) con questo template.
> 
> ```
>     {% set output = namespace(sensor_power_off=[],result=[]) %}
>     {%- set list =          [
> 			'switch.shelly1pm_98cdac2fae5e',
>       'switch.shelly1pm_485519023baf',
> 			'switch.shelly1pm_76df3c',
> 			'climate.condizionatore_aria_matrimoniale',
>       'climate.condizionatore_aria_niccolo',
>       'climate.condizionatore_aria_emma',
> 			'switch.shelly1pm_76b488',
> 			'switch.shelly1pm_76606b',
>       'switch.shelly1pm_765fc7',
>       'switch.shelly1pm_76e76d',
>       'switch.shelly1pm_765dbf',
>       'switch.shelly1pm_766078'
>          ] -%}
>     {%- set filter = states| selectattr('entity_id', 'in', list) |rejectattr('state', 'in',['off', 'unavailable', 'unknown'])|map(attribute='entity_id')|list-%}
>     {%-  for on_power_off in list if on_power_off in filter  -%}
>         {% set id = device_id(on_power_off)%}
>         ID DISCPOSITIVO {{ id }}
>         {%- set sensor_power =expand(device_entities(id))|selectattr('entity_id', 'match', 'sensor.')|selectattr('attributes.device_class', 'defined')| selectattr('attributes.device_class', 'eq', 'power') | map(attribute='entity_id')|list %}
>         SENSORE POWER {{ sensor_power }}
>         {%- for power in sensor_power if states(power)|int(0) < 15-%}
>         ASSORBIMENTO INFERIORE AI 15w:  {{ states(power) }} w
>             {%- set output.sensor_power_off = output.sensor_power_off + [on_power_off] -%}
>         {% endfor %}
>     {% endfor %}
>     {% for t in list if t in filter and not t in output.sensor_power_off %}
>         RISULTATO CORRETTO:{{t}}
>     {% endfor %}
> ```

Ci siamo.
Non vede la lista, il risultato del primo template e' unknown.
Gli shelly sono integrati con integrazione ufficiale.
Mentre il risultato dell'altro template sembra essere corretto:
https://i.imgur.com/HKIoKVq.png

**Comment by marco-hacs** [comment]
prova questo

          {% from 'power_control.jinja' import entities_control %}
          {% set power = entities_control() %}
            {{ power }}

se funziona hai errore nel sensore creato e devi controllare che non hai fatto qualche modifica involontaria 

![image](https://github.com/Home-Assistant-Pro-Team/Power-Control/assets/62516592/2d504bdc-ce8f-4236-afb7-2e8327d49714)

Perchè dal risultato della card la lista nel file .jinja è compilata correttamente

**Comment by fiorentino77** [comment]
> prova questo
> 
> ```
>       {% from 'power_control.jinja' import entities_control %}
>       {% set power = entities_control() %}
>         {{ power }}
> ```
> 
> se non funziona hai errore nel sensore creato e devi controllare che non hai fatto qualche modifica involontaria
> 
> ![image](https://user-images.githubusercontent.com/62516592/250290680-2d504bdc-ce8f-4236-afb7-2e8327d49714.png)
> 
> Perchè dal risultato della card la lista nel file .jinja è compilata correttamente

Si funziona.
Di quale sensore parli, quello dell'assorbimento?
Cosi' ci metto mano.

**Comment by marco-hacs** [comment]
quello dello snap. utilizza il template che hai provato che deve restituire la lista. ma da quello che hai scritto prima non ti funziona il sensore (unknow). Comunque è un tuo problema locale non legato al pkg..

ultima cosa da verificare è che da strumento per sviluppatori il sensor.lista_carichi esiste e che non ci sia un'entità doppia

**Comment by fiorentino77** [comment]
> sensor.lista_carichi

Non esiste alcun sensore lista_carichi, il problema e' questo.

**Comment by marco-hacs** [comment]
Prova a ricaricare il file control_power.yaml. Come ti dicevo è un problema locale.

**Comment by fiorentino77** [comment]
> {% from 'power_control.jinja' import entities_control %}
>       {% set power = entities_control() %}
>         {{ power }}

Che strano, ho nuovamente fatto l'upload del file control_power.yaml.
Il risultato di questo funziona:
`{% from 'power_control.jinja' import entities_control %}
      {% set power = entities_control() %}
        {{ power }}`

 ma il sensore da sempre unknown.
Roba da matti.
Non voglio farti perdere altro tempo e ti ringrazio del supporto, non e' scontato.
