### ISSUE TITLE
box "Ritardo ripristino carico" non funzionante 

### ISSUE THREAD

**Issue by alessandrobenevelli** [Home-Assistant-Pro-Team/Power-Control#5]
Ciao, il box in questione che appare cliccando il secondo pulsante (cog) risulta non disponibile e presenta una segnalazione di problema.

Potrebbe esserci qualche errore di configurazione del file control_power.yaml ?

Grazie per l'ottimo lavoro che stai facendo!

Alessandro

<img width="573" alt="Schermata 2023-07-04 alle 20 10 40" src="https://github.com/Home-Assistant-Pro-Team/Power-Control/assets/62119338/35134e2b-8f12-49e1-8f41-3eff5acea55b">

**Comment by marco-hacs** [comment]
Stai usando la card vecchia.
