### ISSUE TITLE
power_comtrol.jinja

### ISSUE THREAD

**Issue by fiorentino77** [Home-Assistant-Pro-Team/Power-Control#6]
Buongiorno,
ho notato che inserendo diversi dispositivi nel file in oggetto il sensore lista carichi va in unknown.
Potreste verificare su una vs copia se la compilazione seguente e' giusta:

`{% macro entities_control() %}
    {% set list_entities =
         [
			'switch.shelly1pm_98cdac2fae5e',
            'switch.shelly1pm_485519023baf',
			'switch.shelly1pm_76df3c',
			'switch.shelly1pm_76b488',
			'switch.shelly1pm_76606b',
			'switch.shelly1pm_765fc7',
      'switch.shelly1pm_76e76d',
      'switch.shelly1pm_765dbf',
      'switch.shelly1pm_766078'
         ]
    %}
    {% for d in list_entities %}
        {{ d }}
    {% endfor %}
{% endmacro %}`

Sulla mia da "unknown"

mentre cosi':

`{% macro entities_control() %}
    {% set list_entities =
         [
         'switch.shelly1pm_98cdac2fae5e',
               'switch.shelly1pm_485519023baf',
   			'switch.shelly1pm_76df3c',
   			'switch.shelly1pm_76b488',
   			'switch.shelly1pm_76606b',
   			'switch.shelly1pm_765fc7'
            ]`

tutto risulta corretto.
Apparentemente non cambia nulla, solo il numero delle entita' nella lista.
Grazie mille per il supporto.

**Comment by marco-hacs** [comment]
Hai ragione. Il sensore salva la lista nel suo stato e questo ha un limite di 255 caratteri. Questo problema si risolve salvando su attributo. Sono in partenza se riesco aggiorno oggi altrimenti se parla tra una decina di giorni.

**Comment by marco-hacs** [comment]
Puoi usare la v.1.4 le modifiche le trovi nel commit [3b3bdb](https://github.com/Home-Assistant-Pro-Team/Power-Control/commit/3b3bdb1805e7aa4dc98f23be0b48db4c7116eef0).
